environment:
  nodejs_version: "9"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off
